# Generated by Django 4.0.6 on 2022-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.DecimalField(decimal_places=0, default='87777777777', max_digits=15, verbose_name='Телефон'),
        ),
    ]
