# Generated by Django 4.0.6 on 2022-07-09 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('image', models.ImageField(upload_to='publication_images', verbose_name='Image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('moderation_status', models.CharField(blank=True, choices=[('NOT_MODERATED', 'Not moderated'), ('VALID', 'Moderation valid'), ('INVALID', 'Moderation invalid')], default='NOT_MODERATED', max_length=100, verbose_name='Moderation status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='publications.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
